/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * /topics
         * @description List topics by latest activity
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Topic"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics/trending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * /topics/trending
         * @description List trending topics
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Topic"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/t/{discourse_id}/{topic_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * /t/:discourse_id/:topic_id
         * @description Get information about a topic
         */
        get: operations["get_topic"];
        put?: never;
        /**
         * /t/:discourse_id/:topic_id
         * @description Force refresh a topic
         */
        post: operations["refresh_topic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/t/{discourse_id}/{topic_id}/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * /t/:discourse_id/:topic_id/posts
         * @description Get all posts for a topic
         *     This endpoint is paginated, and uses ?page=1 as the first page
         */
        get: operations["get_posts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/t/{discourse_id}/{topic_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * /t/:discourse_id/:topic_id/summary
         * @description Get summaries from topic
         */
        get: operations["get_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/t/{discourse_id}/{topic_id}/summary/cached": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * /t/:discourse_id/:topic_id/summary/cached
         * @description Latest cached summary, read-only: never triggers generation, 404 when none exists
         */
        get: operations["get_cached_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/t/{discourse_id}/{topic_id}/summary/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * /t/:discourse_id/:topic_id/summary/stream
         * @description SSE stream of an ongoing (or just finished) summary generation
         */
        get: operations["get_summary_stream"];
        put?: never;
        /**
         * /t/:discourse_id/:topic_id/summary/stream
         * @description Start summary generation for a topic (or coalesce onto an ongoing one)
         */
        post: operations["start_summary_stream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/digest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * /digest
         * @description Get the latest forum activity digest
         */
        get: operations["get_digest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * /users
         * @description List users
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * /user/profile
         * @description Get authenticated user's profile
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["UserProfileResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/du/{discourse_id}/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * /du/:discourse_id/:username
         * @description Get user profile
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    discourse_id: string;
                    username: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["DiscourseUserProfile"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/du/{discourse_id}/{username}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * /du/:discourse_id/:username/summary
         * @description Get user summary
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    discourse_id: string;
                    username: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["DiscourseUserSummaryResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/sso/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * /user/sso/providers
         * @description Get available SSO providers
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["SSOProvidersResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/sso/{sso_id}/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * /user/sso/:sso_id/login
         * @description Login with SSO - returns redirect URL
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sso_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["LoginResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/sso/{sso_id}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * /user/sso/:sso_id/callback
         * @description SSO callback endpoint - exchanges code for JWT token
         */
        get: {
            parameters: {
                query: {
                    code: string;
                    _state_param?: string;
                };
                header?: never;
                path: {
                    sso_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["AuthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/token/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * /user/token/validate
         * @description Validate JWT token
         */
        post: {
            parameters: {
                query: {
                    token: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["TokenValidationResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** /user/:user_id
         *     Get a Forum user by its user_id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    user_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * /events
         * @description List events
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["RichCalendarEvent"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * /events/recent
         * @description List recent events
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["RichCalendarEvent"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pm/{issue_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * /pm
         * @description Get PM data
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    issue_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["PMMeetingData"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * /search
         * @description Search everything
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["SearchResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** /admin/reindex */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "X-Admin-Key"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["ReindexResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** /admin/stats */
        get: {
            parameters: {
                query?: never;
                header?: {
                    "X-Admin-Key"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["AdminStatsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/digest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** /admin/digest */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "X-Admin-Key"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["ActivityDigest"];
                    };
                };
            };
        };
        /** /admin/digest */
        delete: {
            parameters: {
                query?: never;
                header?: {
                    "X-Admin-Key"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/topic_summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** /admin/topic_summary */
        delete: {
            parameters: {
                query: {
                    topic_id: number;
                    discourse_id: string;
                };
                header?: {
                    "X-Admin-Key"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/llm/system-prompt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** /admin/llm/system-prompt */
        get: {
            parameters: {
                query?: never;
                header?: {
                    "X-Admin-Key"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["SystemPromptResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/llm/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** /admin/llm/memory */
        get: {
            parameters: {
                query?: never;
                header?: {
                    "X-Admin-Key"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["LlmMemory"][];
                    };
                };
            };
        };
        put?: never;
        /** /admin/llm/memory */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "X-Admin-Key"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["LlmMemoryEntry"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["LlmMemory"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/llm/memory/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** /admin/llm/memory/:entry_id */
        delete: {
            parameters: {
                query?: never;
                header?: {
                    "X-Admin-Key"?: string;
                };
                path: {
                    entry_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/llm/memory/staging": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** /admin/llm/memory/staging */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: {
                    "X-Admin-Key"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["LlmMemoryStaging"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/llm/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    run_type?: string;
                    limit?: number;
                    offset?: number;
                };
                header?: {
                    "X-Admin-Key"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["LlmRun"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/llm/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** /admin/llm/runs/:run_id */
        get: {
            parameters: {
                query?: never;
                header?: {
                    "X-Admin-Key"?: string;
                };
                path: {
                    run_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["LlmRun"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/llm/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** /admin/llm/metrics */
        get: {
            parameters: {
                query?: never;
                header?: {
                    "X-Admin-Key"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["AdminMetricsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/llm/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** /admin/llm/usage */
        get: {
            parameters: {
                query?: {
                    days?: number;
                };
                header?: {
                    "X-Admin-Key"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["LlmUsageResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/llm/per-model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** /admin/llm/per-model */
        get: {
            parameters: {
                query?: {
                    days?: number;
                };
                header?: {
                    "X-Admin-Key"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["LlmModelStatsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/llm/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** /admin/llm/snapshots */
        get: {
            parameters: {
                query?: never;
                header?: {
                    "X-Admin-Key"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["LlmMemorySnapshot"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/llm/curator/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** /admin/llm/curator/trigger */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "X-Admin-Key"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["CuratorTriggerResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/llm/curator/last": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** /admin/llm/curator/last */
        get: {
            parameters: {
                query?: never;
                header?: {
                    "X-Admin-Key"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["LlmRun"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhook/discourse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * /webhook/discourse
         * @description Handle Discourse webhook events
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    "X-Discourse-Instance": string;
                    "X-Discourse-Event": string;
                    "X-Discourse-Event-Signature": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/octet-stream": string;
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityDigest */
        ActivityDigest: {
            /** Format: int32 */
            digest_id: number;
            /** Format: date-time */
            period_start: string;
            /** Format: date-time */
            period_end: string;
            digest_text: string;
            topics_included?: unknown;
            /** Format: date-time */
            created_at: string;
        };
        /** AdminMetricsResponse */
        AdminMetricsResponse: {
            /** Format: int64 */
            total_runs: number;
            /** Format: double */
            success_rate: number;
            /** Format: double */
            avg_duration_ms: number;
            /** Format: double */
            avg_total_tokens: number;
            runs_by_type: unknown;
            runs_by_day: unknown;
            /** Format: int64 */
            total_tokens_all_time: number;
        };
        /** AdminStatsResponse */
        AdminStatsResponse: {
            /** Format: int64 */
            database_topics: number;
            /** Format: int64 */
            database_posts: number;
            /** Format: int64 */
            meilisearch_documents?: number;
        };
        /** AuthResponse */
        AuthResponse: {
            token: string;
            user: components["schemas"]["User"];
            /** Format: int64 */
            expires_at: number;
        };
        /** CuratorOutput */
        CuratorOutput: {
            memory_updates: components["schemas"]["MemoryUpdate"][];
            memory_removals: string[];
            snapshot_summary: string;
            action_log: string;
        };
        /** CuratorTriggerResponse */
        CuratorTriggerResponse: {
            success: boolean;
            message: string;
            output?: components["schemas"]["CuratorOutput"];
        };
        /** DiscourseBadge */
        DiscourseBadge: {
            /** Format: uint32 */
            id: number;
            name: string;
            description: string;
            /** Format: uint32 */
            grant_count: number;
            allow_title: boolean;
            multiple_grant: boolean;
            icon: string;
            image_url?: string;
            listable: boolean;
            enabled: boolean;
            /** Format: uint32 */
            badge_grouping_id: number;
            system: boolean;
            slug: string;
            manually_grantable: boolean;
            show_in_post_header: boolean;
            /** Format: uint32 */
            badge_type_id: number;
        };
        /** DiscourseBadgeType */
        DiscourseBadgeType: {
            /** Format: uint32 */
            id: number;
            name: string;
            /** Format: uint32 */
            sort_order: number;
        };
        /** DiscourseDetailedUser */
        DiscourseDetailedUser: {
            /** Format: int32 */
            id: number;
            username: string;
            name?: string;
            avatar_template?: string;
            last_posted_at?: string;
            last_seen_at?: string;
            created_at?: string;
            ignored?: boolean;
            muted?: boolean;
            can_ignore_user?: boolean;
            can_mute_user?: boolean;
            can_send_private_messages?: boolean;
            can_send_private_message_to_user?: boolean;
            /** Format: uint32 */
            trust_level?: number;
            moderator?: boolean;
            admin?: boolean;
            title?: string;
            /** Format: uint32 */
            badge_count?: number;
            custom_fields?: unknown;
            /** Format: uint32 */
            time_read?: number;
            /** Format: uint32 */
            recent_time_read?: number;
            /** Format: uint32 */
            primary_group_id?: number;
            primary_group_name?: string;
            /** Format: uint32 */
            flair_group_id?: number;
            flair_name?: string;
            flair_url?: string;
            flair_bg_color?: string;
            flair_color?: string;
            featured_topic?: unknown;
            can_edit?: boolean;
            can_edit_username?: boolean;
            can_edit_email?: boolean;
            can_edit_name?: boolean;
            /** Format: uint32 */
            uploaded_avatar_id?: number;
            /** Format: uint32 */
            pending_count?: number;
            /** Format: uint32 */
            profile_view_count?: number;
            can_upload_profile_header?: boolean;
            can_upload_user_card_background?: boolean;
            /** Format: uint32 */
            gravatar_avatar_upload_id?: number;
            gravatar_avatar_template?: string;
            /** Format: uint32 */
            custom_avatar_upload_id?: number;
            custom_avatar_template?: string;
            featured_user_badge_ids?: number[];
            invited_by?: unknown;
            groups?: unknown[];
            profile_hidden?: boolean;
        };
        /** DiscourseLink */
        DiscourseLink: {
            url: string;
            title?: string;
            /** Format: uint32 */
            clicks: number;
            /** Format: uint32 */
            post_number: number;
            /** Format: uint32 */
            topic_id: number;
        };
        /** DiscourseReply */
        DiscourseReply: {
            /** Format: uint32 */
            post_number: number;
            /** Format: uint32 */
            like_count: number;
            created_at: string;
            /** Format: uint32 */
            topic_id: number;
        };
        /** DiscourseTopCategory */
        DiscourseTopCategory: {
            /** Format: uint32 */
            topic_count: number;
            /** Format: uint32 */
            post_count: number;
            /** Format: uint32 */
            id: number;
            name: string;
            color: string;
            text_color: string;
            slug: string;
            read_restricted: boolean;
            /** Format: uint32 */
            parent_category_id?: number;
        };
        /** DiscourseTopic */
        DiscourseTopic: {
            /** Format: uint32 */
            id: number;
            title: string;
            fancy_title: string;
            slug: string;
            /** Format: uint32 */
            posts_count: number;
            /** Format: uint32 */
            category_id: number;
            /** Format: uint32 */
            like_count: number;
            created_at: string;
        };
        /** DiscourseUser */
        DiscourseUser: {
            /** Format: int32 */
            id: number;
            username: string;
            name?: string;
            avatar_template?: string;
            admin?: boolean;
            moderator?: boolean;
            /** Format: uint32 */
            trust_level?: number;
            extra: unknown;
        };
        /** DiscourseUserBadge */
        DiscourseUserBadge: {
            /** Format: uint32 */
            id: number;
            granted_at?: string;
            created_at?: string;
            /** Format: uint32 */
            count?: number;
            /** Format: uint32 */
            badge_id?: number;
            /** Format: int32 */
            user_id?: number;
            /** Format: int32 */
            granted_by_id?: number;
        };
        /** DiscourseUserProfile */
        DiscourseUserProfile: {
            badges?: components["schemas"]["DiscourseUserBadge"][];
            badge_types?: components["schemas"]["DiscourseBadgeType"][];
            users?: components["schemas"]["DiscourseUser"][];
            user: components["schemas"]["DiscourseDetailedUser"];
        };
        /** DiscourseUserStats */
        DiscourseUserStats: {
            /** Format: int32 */
            id: number;
            username: string;
            name?: string;
            /** Format: uint32 */
            count?: number;
            avatar_template: string;
            admin: boolean;
            moderator: boolean;
            /** Format: uint32 */
            trust_level: number;
            flair_name?: string;
            flair_url?: string;
            flair_bg_color?: string;
            flair_color?: string;
            primary_group_name?: string;
        };
        /** DiscourseUserSummary */
        DiscourseUserSummary: {
            /** Format: uint32 */
            likes_given: number;
            /** Format: uint32 */
            likes_received: number;
            /** Format: uint32 */
            topics_entered: number;
            /** Format: uint32 */
            posts_read_count: number;
            /** Format: uint32 */
            days_visited: number;
            /** Format: uint32 */
            topic_count: number;
            /** Format: uint32 */
            post_count: number;
            /** Format: uint32 */
            time_read: number;
            /** Format: uint32 */
            recent_time_read: number;
            can_see_summary_stats: boolean;
            can_see_user_actions: boolean;
            topic_ids: number[];
            replies: components["schemas"]["DiscourseReply"][];
            links: components["schemas"]["DiscourseLink"][];
            most_liked_by_users: components["schemas"]["DiscourseUserStats"][];
            most_liked_users: components["schemas"]["DiscourseUserStats"][];
            most_replied_to_users: components["schemas"]["DiscourseUserStats"][];
            badges: components["schemas"]["DiscourseUserBadge"][];
            top_categories: components["schemas"]["DiscourseTopCategory"][];
        };
        /** DiscourseUserSummaryResponse */
        DiscourseUserSummaryResponse: {
            topics?: components["schemas"]["DiscourseTopic"][];
            badges?: components["schemas"]["DiscourseBadge"][];
            badge_types?: components["schemas"]["DiscourseBadgeType"][];
            users?: components["schemas"]["DiscourseUser"][];
            user_summary?: components["schemas"]["DiscourseUserSummary"];
        };
        /** @enum {string} */
        EventOccurrence: "Single" | "Recurring";
        /** GoogleMeetingData */
        GoogleMeetingData: {
            link: string;
        };
        /** LlmMemory */
        LlmMemory: {
            /** Format: int32 */
            entry_id: number;
            term: string;
            content: string;
            /** @description Array of `MemoryLink` objects: where this term's definition comes from. */
            sources?: unknown;
            /** Format: date-time */
            updated_at: string;
        };
        /** LlmMemoryEntry */
        LlmMemoryEntry: {
            /** Format: int32 */
            entry_id: number;
            term: string;
            content: string;
            sources?: unknown;
        };
        /** LlmMemorySnapshot */
        LlmMemorySnapshot: {
            /** Format: int32 */
            snapshot_id: number;
            /** Format: int32 */
            version: number;
            memory_snapshot: unknown;
            /** Format: uuid */
            curator_run_id?: string;
            summary?: string;
            /** Format: date-time */
            created_at: string;
        };
        /**
         * LlmMemoryStaging
         * @description A staged glossary candidate written by a summarizer/digest run via
         *     `note_candidate`. The curator is the only thing that promotes these into
         *     `llm_memory`, so summarizer prompts are never polluted by unverified
         *     candidates.
         */
        LlmMemoryStaging: {
            /** Format: int32 */
            staging_id: number;
            term: string;
            content: string;
            source_discourse_id?: string;
            /** Format: int32 */
            source_topic_id?: number;
            /** Format: int32 */
            source_post_number?: number;
            link_reason?: string;
            /** Format: date-time */
            created_at: string;
        };
        /** LlmModelStats */
        LlmModelStats: {
            model: string;
            /** Format: int64 */
            runs: number;
            /** Format: double */
            avg_prompt_tokens: number;
            /** Format: double */
            avg_completion_tokens: number;
            /** Format: double */
            avg_total_tokens: number;
            /** Format: int64 */
            total_tokens: number;
        };
        /** LlmModelStatsResponse */
        LlmModelStatsResponse: {
            models: components["schemas"]["LlmModelStats"][];
        };
        /** LlmRun */
        LlmRun: {
            /** Format: uuid */
            run_id: string;
            run_type: string;
            discourse_id?: string;
            /** Format: int32 */
            topic_id?: number;
            /** Format: int32 */
            prompt_tokens?: number;
            /** Format: int32 */
            completion_tokens?: number;
            /** Format: int32 */
            total_tokens?: number;
            /** Format: int32 */
            reasoning_tokens?: number;
            model_used?: string;
            /** Format: int32 */
            tool_calls?: number;
            /** Format: int32 */
            tool_rounds?: number;
            /** Format: int32 */
            duration_ms?: number;
            outcome: string;
            error?: string;
            metadata?: unknown;
            trace?: unknown;
            /** Format: date-time */
            created_at: string;
        };
        /** LlmUsageDay */
        LlmUsageDay: {
            date: string;
            run_type: string;
            model_used: string;
            /** Format: int64 */
            prompt_tokens: number;
            /** Format: int64 */
            completion_tokens: number;
            /** Format: int64 */
            total_tokens: number;
            /** Format: int64 */
            runs: number;
            /** Format: int64 */
            failures: number;
        };
        /** LlmUsageResponse */
        LlmUsageResponse: {
            days: components["schemas"]["LlmUsageDay"][];
        };
        /** LoginResponse */
        LoginResponse: {
            redirect_url: string;
        };
        Meeting: components["schemas"]["Meeting_ZoomMeetingData"] | components["schemas"]["Meeting_GoogleMeetingData"] | components["schemas"]["Meeting_YoutubeMeetingData"];
        Meeting_GoogleMeetingData: {
            /**
             * @example Google
             * @enum {string}
             */
            type: "Google";
        } & components["schemas"]["GoogleMeetingData"];
        Meeting_YoutubeMeetingData: {
            /**
             * @example Youtube
             * @enum {string}
             */
            type: "Youtube";
        } & components["schemas"]["YoutubeMeetingData"];
        Meeting_ZoomMeetingData: {
            /**
             * @example Zoom
             * @enum {string}
             */
            type: "Zoom";
        } & components["schemas"]["ZoomMeetingData"];
        /** MemoryUpdate */
        MemoryUpdate: {
            term: string;
            content: string;
            sources?: unknown;
        };
        PMMeetingData: components["schemas"]["PMRecurringMeeting"] | components["schemas"]["PMOneOffMeeting"];
        /** PMOccurrence */
        PMOccurrence: {
            /** Format: uint32 */
            occurrence_number: number;
            /** Format: uint32 */
            issue_number?: number;
            issue_title?: string;
            discourse_topic_id?: string;
            /** Format: date-time */
            start_time?: string;
            /** Format: uint32 */
            duration?: number;
            skip_youtube_upload?: boolean;
            youtube_upload_processed?: boolean;
            transcript_processed?: boolean;
            /** Format: uint32 */
            upload_attempt_count?: number;
            /** Format: uint32 */
            transcript_attempt_count?: number;
            /** Format: uint32 */
            telegram_message_id?: number;
            youtube_streams_posted_to_discourse?: boolean;
            youtube_streams?: components["schemas"]["PMYoutubeStream"][];
            extra: {
                [key: string]: unknown;
            };
        };
        /** PMOneOffMeeting */
        PMOneOffMeeting: {
            discourse_topic_id?: string;
            issue_title?: string;
            /** Format: date-time */
            start_time?: string;
            /** Format: uint32 */
            duration?: number;
            /** Format: uint32 */
            issue_number?: number;
            meeting_id?: string;
            youtube_upload_processed?: boolean;
            transcript_processed?: boolean;
            /** Format: uint32 */
            upload_attempt_count?: number;
            /** Format: uint32 */
            transcript_attempt_count?: number;
            calendar_event_id?: string;
            /** Format: uint32 */
            telegram_message_id?: number;
            extra: {
                [key: string]: unknown;
            };
        };
        /** PMRecurringMeeting */
        PMRecurringMeeting: {
            meeting_id?: string;
            is_recurring?: boolean;
            occurrence_rate?: string;
            call_series?: string;
            zoom_link?: string;
            calendar_event_id?: string;
            occurrences?: components["schemas"]["PMOccurrence"][];
            extra: {
                [key: string]: unknown;
            };
        };
        /** PMYoutubeStream */
        PMYoutubeStream: {
            stream_url?: string;
            /** Format: date-time */
            scheduled_time?: string;
            extra: {
                [key: string]: unknown;
            };
        };
        /** Post */
        Post: {
            discourse_id: string;
            /** Format: int32 */
            post_id: number;
            /** Format: int32 */
            topic_id: number;
            /** Format: int32 */
            user_id: number;
            /** Format: int32 */
            post_number: number;
            /** Format: date-time */
            updated_at?: string;
            /** Format: date-time */
            created_at?: string;
            cooked?: string;
            post_url?: string;
            extra?: unknown;
        };
        /** PostsResponse */
        PostsResponse: {
            posts: components["schemas"]["Post"][];
            has_more: boolean;
        };
        /** ReindexResponse */
        ReindexResponse: {
            success: boolean;
            message: string;
            /** Format: int32 */
            topics_processed: number;
            /** Format: int32 */
            posts_processed: number;
            /** Format: int32 */
            errors: number;
        };
        /** RichCalendarEvent */
        RichCalendarEvent: {
            summary?: string;
            description?: string;
            uid?: string;
            /** Format: date-time */
            last_modified?: string;
            /** Format: date-time */
            created?: string;
            /** Format: date-time */
            start?: string;
            occurance: components["schemas"]["EventOccurrence"];
            meetings: components["schemas"]["Meeting"][];
            pm_data?: components["schemas"]["PMMeetingData"];
            /** Format: uint32 */
            pm_number?: number;
        };
        /** SSOProvidersResponse */
        SSOProvidersResponse: {
            providers: string[];
        };
        /** SearchResponse */
        SearchResponse: Record<string, never>;
        /** StreamingResponse */
        StreamingResponse: {
            content: string;
            is_complete: boolean;
            /** @description Discard all previously received content; generation restarted. */
            is_reset: boolean;
            error?: string;
            tool_activity?: string;
            tool_call?: components["schemas"]["ToolCallUpdate"];
        };
        /** SummaryStartResponse */
        SummaryStartResponse: {
            status: components["schemas"]["SummaryStartStatus"];
            /** Format: int32 */
            topic_id: number;
            discourse_id: string;
            summary?: string;
        };
        /** @enum {string} */
        SummaryStartStatus: "existing" | "started" | "ongoing";
        /** SystemPromptResponse */
        SystemPromptResponse: {
            summary_prompt: string;
            digest_prompt: string;
            curator_prompt: string;
        };
        /** TokenValidationResponse */
        TokenValidationResponse: {
            valid: boolean;
            user?: components["schemas"]["UserInfo"];
            /** Format: int64 */
            expires_at?: number;
        };
        /**
         * ToolCallUpdate
         * @description Progress of a single tool invocation made by the model, streamed to
         *     subscribers as it starts and again when it resolves (matched by `call_id`).
         */
        ToolCallUpdate: {
            call_id: string;
            tool: string;
            label: string;
            /** @description "running", "ok", or "error" */
            status: string;
            detail?: string;
        };
        /** Topic */
        Topic: {
            discourse_id: string;
            /** Format: int32 */
            topic_id: number;
            title: string;
            slug: string;
            /** Format: int32 */
            post_count: number;
            /** Format: int32 */
            view_count: number;
            /** Format: int32 */
            like_count: number;
            image_url?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_post_at?: string;
            /** Format: date-time */
            bumped_at?: string;
            /** Format: int32 */
            pm_issue?: number;
            extra?: unknown;
        };
        /** TopicSummary */
        TopicSummary: {
            /** Format: int32 */
            summary_id: number;
            discourse_id: string;
            /** Format: int32 */
            topic_id: number;
            /** Format: date-time */
            based_on: string;
            /** Format: int32 */
            based_on_post_number?: number;
            summary_text: string;
            summary_json?: unknown;
            /** Format: date-time */
            created_at: string;
        };
        /** User */
        User: {
            /** Format: uuid */
            user_id: string;
            username?: string;
            display_name?: string;
            email?: string;
            avatar_url?: string;
            sso_provider: string;
            sso_user_id: string;
            extras: unknown;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            last_login_at?: string;
        };
        /** UserInfo */
        UserInfo: {
            sub: string;
            email: string;
            name: string;
        };
        /** UserProfileResponse */
        UserProfileResponse: {
            user_id: string;
            email: string;
            display_name?: string;
            avatar_url?: string;
            created_at: string;
            provider: string;
            /** Format: int64 */
            expires_at: number;
            token_expiring_soon: boolean;
        };
        /** YoutubeMeetingData */
        YoutubeMeetingData: {
            link: string;
        };
        /** ZoomMeetingData */
        ZoomMeetingData: {
            link: string;
            meeting_id?: string;
            passcode?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_topic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                discourse_id: string;
                topic_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Topic"];
                };
            };
        };
    };
    refresh_topic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                discourse_id: string;
                topic_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": unknown;
                };
            };
        };
    };
    get_posts: {
        parameters: {
            query: {
                page: number;
                size?: number;
            };
            header?: never;
            path: {
                discourse_id: string;
                topic_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["PostsResponse"];
                };
            };
        };
    };
    get_summary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                discourse_id: string;
                topic_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["TopicSummary"];
                };
            };
        };
    };
    get_cached_summary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                discourse_id: string;
                topic_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["TopicSummary"];
                };
            };
        };
    };
    get_summary_stream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                discourse_id: string;
                topic_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["StreamingResponse"][];
                };
            };
        };
    };
    start_summary_stream: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: {
                "X-Admin-Key"?: string;
            };
            path: {
                discourse_id: string;
                topic_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["SummaryStartResponse"];
                };
            };
        };
    };
    get_digest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["ActivityDigest"];
                };
            };
        };
    };
}
