name: ethforum
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ethforum
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ethforum"]
      interval: 5s
      timeout: 5s
      retries: 5
  meilisearch:
    image: getmeili/meilisearch:v1.3
    environment:
      MEILI_MASTER_KEY: ${MEILI_KEY}
      MEILI_NO_ANALYTICS: "true"
    ports:
      - "7700:7700"
    volumes:
      - meili-data:/data.ms
    healthcheck:
      test: set -o pipefail;curl -fsS http://localhost:7700/health | grep -q '{"status":"available"}'
      retries: 3
      timeout: 5s

volumes:
  pg-data:
    driver: local
  meili-data:
    driver: local
