/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin/route'
import { Route as IndexImport } from './routes/index'
import { Route as SIndexImport } from './routes/s/index'
import { Route as RIndexImport } from './routes/r/index'
import { Route as CIndexImport } from './routes/c/index'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as AdminRunsImport } from './routes/admin/runs'
import { Route as AdminPromptsImport } from './routes/admin/prompts'
import { Route as AdminMemoryImport } from './routes/admin/memory'
import { Route as AdminActionsImport } from './routes/admin/actions'
import { Route as PmIssueIdIndexImport } from './routes/pm/$issueId/index'
import { Route as SsoProviderIdCallbackImport } from './routes/sso/$providerId/callback'
import { Route as UDiscourseIdUserIdIndexImport } from './routes/u/$discourseId/$userId/index'
import { Route as TDiscourseIdTopicIdIndexImport } from './routes/t/$discourseId/$topicId/index'

// Create/Update Routes

const AdminRouteRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SIndexRoute = SIndexImport.update({
  id: '/s/',
  path: '/s/',
  getParentRoute: () => rootRoute,
} as any)

const RIndexRoute = RIndexImport.update({
  id: '/r/',
  path: '/r/',
  getParentRoute: () => rootRoute,
} as any)

const CIndexRoute = CIndexImport.update({
  id: '/c/',
  path: '/c/',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminRunsRoute = AdminRunsImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminPromptsRoute = AdminPromptsImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminMemoryRoute = AdminMemoryImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminActionsRoute = AdminActionsImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => AdminRouteRoute,
} as any)

const PmIssueIdIndexRoute = PmIssueIdIndexImport.update({
  id: '/pm/$issueId/',
  path: '/pm/$issueId/',
  getParentRoute: () => rootRoute,
} as any)

const SsoProviderIdCallbackRoute = SsoProviderIdCallbackImport.update({
  id: '/sso/$providerId/callback',
  path: '/sso/$providerId/callback',
  getParentRoute: () => rootRoute,
} as any)

const UDiscourseIdUserIdIndexRoute = UDiscourseIdUserIdIndexImport.update({
  id: '/u/$discourseId/$userId/',
  path: '/u/$discourseId/$userId/',
  getParentRoute: () => rootRoute,
} as any)

const TDiscourseIdTopicIdIndexRoute = TDiscourseIdTopicIdIndexImport.update({
  id: '/t/$discourseId/$topicId/',
  path: '/t/$discourseId/$topicId/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRoute
    }
    '/admin/actions': {
      id: '/admin/actions'
      path: '/actions'
      fullPath: '/admin/actions'
      preLoaderRoute: typeof AdminActionsImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/memory': {
      id: '/admin/memory'
      path: '/memory'
      fullPath: '/admin/memory'
      preLoaderRoute: typeof AdminMemoryImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/prompts': {
      id: '/admin/prompts'
      path: '/prompts'
      fullPath: '/admin/prompts'
      preLoaderRoute: typeof AdminPromptsImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/runs': {
      id: '/admin/runs'
      path: '/runs'
      fullPath: '/admin/runs'
      preLoaderRoute: typeof AdminRunsImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/c/': {
      id: '/c/'
      path: '/c'
      fullPath: '/c'
      preLoaderRoute: typeof CIndexImport
      parentRoute: typeof rootRoute
    }
    '/r/': {
      id: '/r/'
      path: '/r'
      fullPath: '/r'
      preLoaderRoute: typeof RIndexImport
      parentRoute: typeof rootRoute
    }
    '/s/': {
      id: '/s/'
      path: '/s'
      fullPath: '/s'
      preLoaderRoute: typeof SIndexImport
      parentRoute: typeof rootRoute
    }
    '/sso/$providerId/callback': {
      id: '/sso/$providerId/callback'
      path: '/sso/$providerId/callback'
      fullPath: '/sso/$providerId/callback'
      preLoaderRoute: typeof SsoProviderIdCallbackImport
      parentRoute: typeof rootRoute
    }
    '/pm/$issueId/': {
      id: '/pm/$issueId/'
      path: '/pm/$issueId'
      fullPath: '/pm/$issueId'
      preLoaderRoute: typeof PmIssueIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/t/$discourseId/$topicId/': {
      id: '/t/$discourseId/$topicId/'
      path: '/t/$discourseId/$topicId'
      fullPath: '/t/$discourseId/$topicId'
      preLoaderRoute: typeof TDiscourseIdTopicIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/u/$discourseId/$userId/': {
      id: '/u/$discourseId/$userId/'
      path: '/u/$discourseId/$userId'
      fullPath: '/u/$discourseId/$userId'
      preLoaderRoute: typeof UDiscourseIdUserIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface AdminRouteRouteChildren {
  AdminActionsRoute: typeof AdminActionsRoute
  AdminMemoryRoute: typeof AdminMemoryRoute
  AdminPromptsRoute: typeof AdminPromptsRoute
  AdminRunsRoute: typeof AdminRunsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminActionsRoute: AdminActionsRoute,
  AdminMemoryRoute: AdminMemoryRoute,
  AdminPromptsRoute: AdminPromptsRoute,
  AdminRunsRoute: AdminRunsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/actions': typeof AdminActionsRoute
  '/admin/memory': typeof AdminMemoryRoute
  '/admin/prompts': typeof AdminPromptsRoute
  '/admin/runs': typeof AdminRunsRoute
  '/admin/': typeof AdminIndexRoute
  '/c': typeof CIndexRoute
  '/r': typeof RIndexRoute
  '/s': typeof SIndexRoute
  '/sso/$providerId/callback': typeof SsoProviderIdCallbackRoute
  '/pm/$issueId': typeof PmIssueIdIndexRoute
  '/t/$discourseId/$topicId': typeof TDiscourseIdTopicIdIndexRoute
  '/u/$discourseId/$userId': typeof UDiscourseIdUserIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/actions': typeof AdminActionsRoute
  '/admin/memory': typeof AdminMemoryRoute
  '/admin/prompts': typeof AdminPromptsRoute
  '/admin/runs': typeof AdminRunsRoute
  '/admin': typeof AdminIndexRoute
  '/c': typeof CIndexRoute
  '/r': typeof RIndexRoute
  '/s': typeof SIndexRoute
  '/sso/$providerId/callback': typeof SsoProviderIdCallbackRoute
  '/pm/$issueId': typeof PmIssueIdIndexRoute
  '/t/$discourseId/$topicId': typeof TDiscourseIdTopicIdIndexRoute
  '/u/$discourseId/$userId': typeof UDiscourseIdUserIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/actions': typeof AdminActionsRoute
  '/admin/memory': typeof AdminMemoryRoute
  '/admin/prompts': typeof AdminPromptsRoute
  '/admin/runs': typeof AdminRunsRoute
  '/admin/': typeof AdminIndexRoute
  '/c/': typeof CIndexRoute
  '/r/': typeof RIndexRoute
  '/s/': typeof SIndexRoute
  '/sso/$providerId/callback': typeof SsoProviderIdCallbackRoute
  '/pm/$issueId/': typeof PmIssueIdIndexRoute
  '/t/$discourseId/$topicId/': typeof TDiscourseIdTopicIdIndexRoute
  '/u/$discourseId/$userId/': typeof UDiscourseIdUserIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/actions'
    | '/admin/memory'
    | '/admin/prompts'
    | '/admin/runs'
    | '/admin/'
    | '/c'
    | '/r'
    | '/s'
    | '/sso/$providerId/callback'
    | '/pm/$issueId'
    | '/t/$discourseId/$topicId'
    | '/u/$discourseId/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/actions'
    | '/admin/memory'
    | '/admin/prompts'
    | '/admin/runs'
    | '/admin'
    | '/c'
    | '/r'
    | '/s'
    | '/sso/$providerId/callback'
    | '/pm/$issueId'
    | '/t/$discourseId/$topicId'
    | '/u/$discourseId/$userId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/actions'
    | '/admin/memory'
    | '/admin/prompts'
    | '/admin/runs'
    | '/admin/'
    | '/c/'
    | '/r/'
    | '/s/'
    | '/sso/$providerId/callback'
    | '/pm/$issueId/'
    | '/t/$discourseId/$topicId/'
    | '/u/$discourseId/$userId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  CIndexRoute: typeof CIndexRoute
  RIndexRoute: typeof RIndexRoute
  SIndexRoute: typeof SIndexRoute
  SsoProviderIdCallbackRoute: typeof SsoProviderIdCallbackRoute
  PmIssueIdIndexRoute: typeof PmIssueIdIndexRoute
  TDiscourseIdTopicIdIndexRoute: typeof TDiscourseIdTopicIdIndexRoute
  UDiscourseIdUserIdIndexRoute: typeof UDiscourseIdUserIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  CIndexRoute: CIndexRoute,
  RIndexRoute: RIndexRoute,
  SIndexRoute: SIndexRoute,
  SsoProviderIdCallbackRoute: SsoProviderIdCallbackRoute,
  PmIssueIdIndexRoute: PmIssueIdIndexRoute,
  TDiscourseIdTopicIdIndexRoute: TDiscourseIdTopicIdIndexRoute,
  UDiscourseIdUserIdIndexRoute: UDiscourseIdUserIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/c/",
        "/r/",
        "/s/",
        "/sso/$providerId/callback",
        "/pm/$issueId/",
        "/t/$discourseId/$topicId/",
        "/u/$discourseId/$userId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin/route.tsx",
      "children": [
        "/admin/actions",
        "/admin/memory",
        "/admin/prompts",
        "/admin/runs",
        "/admin/"
      ]
    },
    "/admin/actions": {
      "filePath": "admin/actions.tsx",
      "parent": "/admin"
    },
    "/admin/memory": {
      "filePath": "admin/memory.tsx",
      "parent": "/admin"
    },
    "/admin/prompts": {
      "filePath": "admin/prompts.tsx",
      "parent": "/admin"
    },
    "/admin/runs": {
      "filePath": "admin/runs.tsx",
      "parent": "/admin"
    },
    "/admin/": {
      "filePath": "admin/index.tsx",
      "parent": "/admin"
    },
    "/c/": {
      "filePath": "c/index.tsx"
    },
    "/r/": {
      "filePath": "r/index.tsx"
    },
    "/s/": {
      "filePath": "s/index.tsx"
    },
    "/sso/$providerId/callback": {
      "filePath": "sso/$providerId/callback.tsx"
    },
    "/pm/$issueId/": {
      "filePath": "pm/$issueId/index.tsx"
    },
    "/t/$discourseId/$topicId/": {
      "filePath": "t/$discourseId/$topicId/index.tsx"
    },
    "/u/$discourseId/$userId/": {
      "filePath": "u/$discourseId/$userId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
